name: Lint & Test
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13-alpine
        ports:
          - 5432
        env:
          POSTGRES_USER: username
          POSTGRES_PASS: pass
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_DB: relay
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      relay:
        image: ghcr.io/rust-playground/relay-rs:0.11.0
        ports:
          - 8080:8080
        env:
          RUST_LOG: "debug"
          DATABASE_URL: "postgres://username:pass@postgres:5432/relay?sslmode=disable"

    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.x

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Restore Cache
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-v1-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-v1-go-

      - name: Test
        run: make test.ci
        env:
          RELAY_URL: "http://localhost:8080"

  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
